site_name: Keymail
repo_url: https://github.com/alcesleo/keymail/
pages:
- ['index.md', 'Home']
- ['getting-started.md', 'Getting Started']
- ['advanced.md', 'Advanced']
- ['faq.md', 'FAQ']
- ['developing.md', 'Developing']
- ['project/vision.md', 'Project', 'Vision']
- ['project/structure.md', 'Project', 'Structure']
- ['project/diary.md', 'Project', 'Diary']
