site_name: Keymail
repo_url: https://github.com/alcesleo/keymail/
pages:
- ['index.md', 'Home']
- ['usage/getting-started.md', 'Usage', 'Getting Started']
- ['usage/faq.md', 'Usage', 'FAQ']
- ['development.md', 'Development']
